### ISSUE TITLE
关于 session 的问题

### ISSUE THREAD

**Issue by EnoND** [node-webot/wechat-enterprise#21]
希望可以解决
s1:服务端和通过公众号发消息的用户之间的session
和
s2:服务端和浏览器端之间的session
互通

可以在 事件推送的时候就保存用户状态到s2

**Comment by JacksonTian** [comment]
这样子用：
```
req.sessionStore.get(openid, function (err, data) {
  // todo
});
```

可以在普通网页里访问到用户通过微信访问公共号时保存的session。

**Comment by fredwang222** [comment]
我发现用了上面的代码仍然拿不到session数据（data为 undefined),  代码如下（在单独的网页不行，为简单就直接将该代码直接加在后面扔不行，-新人望不见笑),  这样做是否合理，能否 帮看？最好有一个可以运行的代码（普通网页）供学习参考，谢谢！

app.use('/wechat', wechat('some token', wechat.text(function (info, req, res, next) {
//  console.log(info.FromUserName);
  if (info.Content === '=') {
    req.wxsession.text = req.wxsession.text || [];
    var exp = req.wxsession.text.join('');
    res.reply('result: ' + eval(exp));
  } else if (info.Content === 'destroy') {
    req.wxsession.destroy();
    res.reply('....');
  } else {
    req.wxsession.text = req.wxsession.text || [];
    req.wxsession.text.push(info.Content);
    res.reply('..' + info.Content);
    req.sessionStore.get(info.FromUserName, function(err, data) {
      console.log(data);
    });
  }
})));

**Comment by JacksonTian** [comment]
第一次访问 没有响应之前 req.sessionStore.get是拿不到数据的。

**Comment by JacksonTian** [comment]
req.sessionStore.get(info.FromUserName, function(err, data) {
console.log(data);
});

适合在普通页面中去拿数据。在/wechat的路径下拿这个数据没有意义。还不如 req.wxsession方便呢
