### ISSUE TITLE
关于 企业号菜单 微信扫一扫 事件推送

### ISSUE THREAD

**Issue by EnoND** [node-webot/wechat-enterprise#22]
企业号 扫一扫 推送的事件中
二维码内容
message.ScanCodeInfo.ScanResult 
把 二维码 中的参数 分隔符 & 给过滤没了。。
比如 http://www.xxx.com?id=ddd&aaa=bbb
会变成 http://www.xxx.com?id=dddaaa=bbb

**Comment by JacksonTian** [comment]
还有这个问题么？

**Comment by EnoND** [comment]
有啊， 我现在的解决办法就是截取字符串  手动添上一个 &

**Comment by JacksonTian** [comment]
能提供下原始报文么。

**Comment by EnoND** [comment]
不太好弄 ，程序已经给客户上了

**Comment by JacksonTian** [comment]
能否用 http://qydev.weixin.qq.com/debug 帮忙构造一个原始xml文件出来么

**Comment by JacksonTian** [comment]
这个bug不能重现 我这边也没法fix

**Comment by linzhengwang** [comment]
@JacksonTian 你好请教一下 关于  "扫码推事件且弹出“消息接收中”提示框的事件推送" 这个事件的流程
 比如是个签到场景, 
1.把签到写入的方法链接生成二维码 
2.企业号应用开启回调,菜单选择 扫描推事件(弹框)
3.然后在回调地址那 接收参数,接受POST数据 解密消息 
4.获取到解密的数据 调用二维码的链接 插入数据库签到?   后面这里我不太明白 想请教下你 正确领导流程

**Comment by JacksonTian** [comment]
@nick-ma 有什么能帮楼上的么。

**Comment by nick-ma** [comment]
@linzhengwang 用不着这么费劲吧。你可以用jsapi来哉HTML5的网页里调起扫一扫的功能，扫成果之后会直接把扫码的结果返回给网页的。后面你就直接调用ajax把数据写到后台就好了。
如果非要用会话界面的扫一扫菜单功能，建议二维码里的信息自己做一下编码，扫过之后自己去后台解码，并进行后续的处理。

**Comment by linzhengwang** [comment]
@nick-ma 感谢啊, JS-SDK的用户需要再进去一层, 而且网页调用有一定延迟性  我想用的是 < "扫码推事件且弹出“消息接收中”提示框的事件推送" >这个功能 用户点菜单 扫完 弹出个小提示 而不用进去网页 这样 用户操作容易体验也好.只是开发麻烦点  因为目前没看有人有具体的例子 就自己在琢磨研究 怎么操作 这个事件回调会比较稳定
