### ISSUE TITLE
文档没有更新，已经不能使用了。

### ISSUE THREAD

**Issue by airyland** [node-webot/wechat-enterprise#25]
http://node-webot.github.io/wechat-enterprise/api.html#api_api_common

`The API property deprecated, Use require("wechat-api") instead`

然后更换成`wechat-api`同样报错不能使用

````javascript
var API = require('wechat-api');
var api = new API('wx*****', '******', '6');

api.getLatestToken(function(err,token){
	console.log(err,token);
});
````

**Comment by nick-ma** [comment]
嗯，文档确实很老了。
现在wechat-enterprise已经拆分了。你要的功能在wechat-enterprise-api这个包里面。
最新版本请安装git上的。

**Comment by na57** [comment]
企业版的api要使用 wechat-enterprise-api

**Comment by airyland** [comment]
那么 wechat-enterprise 的README要说明一下吧，文档要更新一下吧。而wechat-enterprise-api 没有详细文档，所以我只能去翻代码？

**Comment by JacksonTian** [comment]
http://doxmate.cool/node-webot/wechat-enterprise/api.html#api_wechat-enterprise 你看的文档 已经不更新了。 doxmate.cool才是最新的。

**Comment by airyland** [comment]
这是wechat-enterprise的文档。但是不还是没有 wechat-enterprise-api 的文档？

**Comment by JacksonTian** [comment]
http://doxmate.cool
