### ISSUE TITLE
access_token过期处理

### ISSUE THREAD

**Issue by 6jq** [node-webot/wechat-enterprise#31]
不是说 “无需尝试处理access token”吗？ (http://doxmate.cool/node-webot/wechat-enterprise/Getting%20start.html#index_调用API)；
但我调用api.send的时候还是会报 { [WeChatAPIError: access_token expired] name: 'WeChatAPIError', code: 42001 }的错误

**Comment by JacksonTian** [comment]
api.send() ？那是 wechat-enterprise-api的内容了吧？

**Comment by lujq1020** [comment]
对啊。
wechat-enterprise-api中需要access token的接口调用如果采用preRequest进行封装后，就可以直接调用，无需依赖getAccessToken为前置调用。而api中的send方法是使用preRequest封装的，由preRequest处理access token是否过期，调用send应该是不用处理access token，但我调用send方法在access token过期后没有重新获取而是直接抛错。
